#!/usr/bin/env python3
#
# Copyright 2020 Diomidis Spinellis
# Copyright 2021 Konstantinos Foutzopoulos
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""
Generate an Bash script for correcting Greek or Latin text
entered using the wrong keyboard layout.
Depends on:
  `xsel` for clipboard manipulation
  `xdotool` for key inputs
"""


def single_key_replace(source, target):
    """Create a set of replacements for single characters"""
    for i in range(0, len(source)):
        print(f'    str="${{str//{source[i]}/{target[i]}}}"')


def dead_key_replace(dead, source, target):
    """Create a set of replacements for the specified dead key characters"""
    for i in range(0, len(source)):
        print(f'    str="${{str//{dead}{source[i]}/{target[i]}}}"')


def main():
    """
    Generate the Bash script on the standard output
    """
    # Include `sleep` else `xdotool` gets stuck
    print("""#!/usr/bin/env bash
# Ctrl-Alt-G: Fix Greek text entered on Latin keyboard setting
# Auto-generated by greek-latin-fix.py
for cmd in xdotool xsel; do
    if ! type $cmd; then
        notify-send "greek-latin-fix failed" "missing dependencies"
        exit 1
    fi
done
xdotool key ctrl+c
sleep 0.1
str="$(xsel -b -o)"
if [[ "$str" =~ ^[A-Za-z:\;\ ]+$ ]]; then""")

    latin_no_shift = 'abcdefghijklmnopqrstuvwxyz'
    greek_no_shift = 'αβψδεφγηιξκλμνοπ;ρστθωςχυζ'

    latin_shift = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    greek_shift = 'ΑΒΨΔΕΦΓΗΙΞΚΛΜΝΟΠ;ΡΣΤΘΩΣΧΥΖ'

    # Replace English with Greek
    dead_key_replace(";", 'aehioyv', 'άέήίόύώ')
    dead_key_replace(";", 'AEHIOYV', 'ΆΈΉΊΌΎΏ')
    dead_key_replace(":", 'iy', 'ϊϋ')
    dead_key_replace(":", 'IY', 'ΪΫ')

    single_key_replace(latin_no_shift, greek_no_shift)
    single_key_replace(latin_shift, greek_shift)

    print("else")
    # Replace Greek with English

    single_key_replace(greek_no_shift, latin_no_shift)
    single_key_replace(greek_shift, latin_shift)

    # `xdotool` can type ascii text but utf-8 requires escaping
    print("""\
fi
xsel -b -i <<< "$str"
sleep 0.1
xdotool key ctrl+v
""")


if __name__ == "__main__":
    main()
